// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCampus.API.Data;

#nullable disable

namespace SmartCampus.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251214103104_AddAnnouncements")]
    partial class AddAnnouncements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartCampus.API.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Announcement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<Guid?>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CourseId", "CreatedAt");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("SmartCampus.API.Models.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Accuracy")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DistanceFromCenter")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("FlagReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsQrVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SessionId", "StudentId")
                        .IsUnique();

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("SmartCampus.API.Models.AttendanceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<int>("GeofenceRadius")
                        .HasColumnType("int");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("QrCode")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("QrCodeExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("char(36)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("SectionId", "Date");

                    b.ToTable("AttendanceSessions");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Classroom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FeaturesJson")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,7)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Building", "RoomNumber")
                        .IsUnique();

                    b.ToTable("Classrooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1a00001-0001-0001-0001-000000000001"),
                            Building = "A Blok",
                            Capacity = 50,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7092),
                            FeaturesJson = "[\"projector\", \"whiteboard\", \"ac\", \"computer\"]",
                            IsActive = true,
                            Latitude = 41.1055m,
                            Longitude = 29.0250m,
                            RoomNumber = "101",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7172)
                        },
                        new
                        {
                            Id = new Guid("c2a00002-0002-0002-0002-000000000002"),
                            Building = "A Blok",
                            Capacity = 40,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7249),
                            FeaturesJson = "[\"projector\", \"whiteboard\"]",
                            IsActive = true,
                            Latitude = 41.1056m,
                            Longitude = 29.0251m,
                            RoomNumber = "102",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7250)
                        },
                        new
                        {
                            Id = new Guid("c3a00003-0003-0003-0003-000000000003"),
                            Building = "B Blok",
                            Capacity = 60,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7253),
                            FeaturesJson = "[\"projector\", \"whiteboard\", \"ac\", \"lab_computers\"]",
                            IsActive = true,
                            Latitude = 41.1060m,
                            Longitude = 29.0255m,
                            RoomNumber = "201",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7253)
                        },
                        new
                        {
                            Id = new Guid("c4a00004-0004-0004-0004-000000000004"),
                            Building = "B Blok",
                            Capacity = 35,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7262),
                            FeaturesJson = "[\"projector\", \"whiteboard\", \"ac\"]",
                            IsActive = true,
                            Latitude = 41.1061m,
                            Longitude = 29.0256m,
                            RoomNumber = "202",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7263)
                        },
                        new
                        {
                            Id = new Guid("c5a00005-0005-0005-0005-000000000005"),
                            Building = "C Blok",
                            Capacity = 30,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7278),
                            FeaturesJson = "[\"projector\", \"whiteboard\", \"ac\", \"lab_computers\", \"network\"]",
                            IsActive = true,
                            Latitude = 41.1065m,
                            Longitude = 29.0260m,
                            RoomNumber = "Lab-1",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(7278)
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SyllabusUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c0a00001-0001-0001-0001-000000000001"),
                            Code = "BM101",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9022),
                            Credits = 4,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Temel programlama kavramları, değişkenler, döngüler, fonksiyonlar ve nesne yönelimli programlamaya giriş.",
                            ECTS = 6,
                            IsActive = true,
                            Name = "Programlamaya Giriş",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9099)
                        },
                        new
                        {
                            Id = new Guid("c0a00002-0002-0002-0002-000000000002"),
                            Code = "BM201",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9171),
                            Credits = 4,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Diziler, bağlı listeler, yığınlar, kuyruklar, ağaçlar ve graf veri yapıları.",
                            ECTS = 6,
                            IsActive = true,
                            Name = "Veri Yapıları",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9172)
                        },
                        new
                        {
                            Id = new Guid("c0a00003-0003-0003-0003-000000000003"),
                            Code = "BM301",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9175),
                            Credits = 3,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Algoritma analizi, sıralama ve arama algoritmaları, dinamik programlama, açgözlü algoritmalar.",
                            ECTS = 5,
                            IsActive = true,
                            Name = "Algoritmalar",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9175)
                        },
                        new
                        {
                            Id = new Guid("c0a00004-0004-0004-0004-000000000004"),
                            Code = "BM302",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9177),
                            Credits = 3,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "İlişkisel veritabanları, SQL, normalizasyon, indeksleme ve transaction yönetimi.",
                            ECTS = 5,
                            IsActive = true,
                            Name = "Veritabanı Sistemleri",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9178)
                        },
                        new
                        {
                            Id = new Guid("c0a00005-0005-0005-0005-000000000005"),
                            Code = "BM401",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9180),
                            Credits = 3,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Yazılım geliştirme süreçleri, tasarım desenleri, test ve kalite güvencesi.",
                            ECTS = 5,
                            IsActive = true,
                            Name = "Yazılım Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9180)
                        },
                        new
                        {
                            Id = new Guid("c0a00006-0006-0006-0006-000000000006"),
                            Code = "BM402",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9183),
                            Credits = 3,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "HTML, CSS, JavaScript, React, Node.js ve modern web teknolojileri.",
                            ECTS = 5,
                            IsActive = true,
                            Name = "Web Programlama",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9183)
                        },
                        new
                        {
                            Id = new Guid("c0a00007-0007-0007-0007-000000000007"),
                            Code = "EEM101",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9190),
                            Credits = 4,
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Temel elektrik devreleri, Kirchhoff yasaları, Thevenin ve Norton teoremleri.",
                            ECTS = 6,
                            IsActive = true,
                            Name = "Devre Analizi",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9190)
                        },
                        new
                        {
                            Id = new Guid("c0a00008-0008-0008-0008-000000000008"),
                            Code = "EEM201",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9192),
                            Credits = 4,
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Diyotlar, transistörler, opamp'lar ve temel elektronik devreler.",
                            ECTS = 6,
                            IsActive = true,
                            Name = "Elektronik",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 530, DateTimeKind.Utc).AddTicks(9193)
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.CoursePrerequisite", b =>
                {
                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PrerequisiteCourseId")
                        .HasColumnType("char(36)");

                    b.HasKey("CourseId", "PrerequisiteCourseId");

                    b.HasIndex("PrerequisiteCourseId");

                    b.ToTable("CoursePrerequisites");

                    b.HasData(
                        new
                        {
                            CourseId = new Guid("c0a00002-0002-0002-0002-000000000002"),
                            PrerequisiteCourseId = new Guid("c0a00001-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            CourseId = new Guid("c0a00003-0003-0003-0003-000000000003"),
                            PrerequisiteCourseId = new Guid("c0a00002-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            CourseId = new Guid("c0a00004-0004-0004-0004-000000000004"),
                            PrerequisiteCourseId = new Guid("c0a00002-0002-0002-0002-000000000002")
                        },
                        new
                        {
                            CourseId = new Guid("c0a00005-0005-0005-0005-000000000005"),
                            PrerequisiteCourseId = new Guid("c0a00003-0003-0003-0003-000000000003")
                        },
                        new
                        {
                            CourseId = new Guid("c0a00005-0005-0005-0005-000000000005"),
                            PrerequisiteCourseId = new Guid("c0a00004-0004-0004-0004-000000000004")
                        },
                        new
                        {
                            CourseId = new Guid("c0a00006-0006-0006-0006-000000000006"),
                            PrerequisiteCourseId = new Guid("c0a00001-0001-0001-0001-000000000001")
                        },
                        new
                        {
                            CourseId = new Guid("c0a00008-0008-0008-0008-000000000008"),
                            PrerequisiteCourseId = new Guid("c0a00007-0007-0007-0007-000000000007")
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.CourseSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ClassroomId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EnrolledCount")
                        .HasColumnType("int");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ScheduleJson")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("CourseId", "SectionNumber", "Semester", "Year")
                        .IsUnique();

                    b.ToTable("CourseSections");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5ec00001-0001-0001-0001-000000000001"),
                            Capacity = 50,
                            ClassroomId = new Guid("c1a00001-0001-0001-0001-000000000001"),
                            CourseId = new Guid("c0a00001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1456),
                            EnrolledCount = 3,
                            InstructorId = new Guid("fa111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ScheduleJson = "[{\"day\":\"Monday\",\"startTime\":\"09:00\",\"endTime\":\"10:50\"},{\"day\":\"Wednesday\",\"startTime\":\"09:00\",\"endTime\":\"10:50\"}]",
                            SectionNumber = 1,
                            Semester = "Fall",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1530),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("5ec00002-0002-0002-0002-000000000002"),
                            Capacity = 40,
                            ClassroomId = new Guid("c2a00002-0002-0002-0002-000000000002"),
                            CourseId = new Guid("c0a00002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1603),
                            EnrolledCount = 2,
                            InstructorId = new Guid("fa111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ScheduleJson = "[{\"day\":\"Tuesday\",\"startTime\":\"11:00\",\"endTime\":\"12:50\"},{\"day\":\"Thursday\",\"startTime\":\"11:00\",\"endTime\":\"12:50\"}]",
                            SectionNumber = 1,
                            Semester = "Fall",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1603),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("5ec00003-0003-0003-0003-000000000003"),
                            Capacity = 35,
                            ClassroomId = new Guid("c3a00003-0003-0003-0003-000000000003"),
                            CourseId = new Guid("c0a00003-0003-0003-0003-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1608),
                            EnrolledCount = 2,
                            InstructorId = new Guid("fa111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ScheduleJson = "[{\"day\":\"Monday\",\"startTime\":\"13:00\",\"endTime\":\"14:50\"},{\"day\":\"Wednesday\",\"startTime\":\"13:00\",\"endTime\":\"14:50\"}]",
                            SectionNumber = 1,
                            Semester = "Fall",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1609),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("5ec00004-0004-0004-0004-000000000004"),
                            Capacity = 35,
                            ClassroomId = new Guid("c4a00004-0004-0004-0004-000000000004"),
                            CourseId = new Guid("c0a00004-0004-0004-0004-000000000004"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1612),
                            EnrolledCount = 1,
                            InstructorId = new Guid("fa111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ScheduleJson = "[{\"day\":\"Tuesday\",\"startTime\":\"14:00\",\"endTime\":\"15:50\"},{\"day\":\"Thursday\",\"startTime\":\"14:00\",\"endTime\":\"15:50\"}]",
                            SectionNumber = 1,
                            Semester = "Fall",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1612),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("5ec00005-0005-0005-0005-000000000005"),
                            Capacity = 30,
                            ClassroomId = new Guid("c5a00005-0005-0005-0005-000000000005"),
                            CourseId = new Guid("c0a00006-0006-0006-0006-000000000006"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1615),
                            EnrolledCount = 2,
                            InstructorId = new Guid("fa111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ScheduleJson = "[{\"day\":\"Friday\",\"startTime\":\"10:00\",\"endTime\":\"12:50\"}]",
                            SectionNumber = 1,
                            Semester = "Fall",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1616),
                            Year = 2025
                        },
                        new
                        {
                            Id = new Guid("5ec00006-0006-0006-0006-000000000006"),
                            Capacity = 45,
                            ClassroomId = new Guid("c1a00001-0001-0001-0001-000000000001"),
                            CourseId = new Guid("c0a00007-0007-0007-0007-000000000007"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1619),
                            EnrolledCount = 1,
                            InstructorId = new Guid("fa222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            ScheduleJson = "[{\"day\":\"Monday\",\"startTime\":\"15:00\",\"endTime\":\"16:50\"},{\"day\":\"Wednesday\",\"startTime\":\"15:00\",\"endTime\":\"16:50\"}]",
                            SectionNumber = 1,
                            Semester = "Fall",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(1619),
                            Year = 2025
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "BM",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 544, DateTimeKind.Utc).AddTicks(630),
                            Description = "Bilgisayar Mühendisliği Bölümü",
                            Faculty = "Mühendislik Fakültesi",
                            IsActive = true,
                            Name = "Bilgisayar Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 544, DateTimeKind.Utc).AddTicks(723)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "EEM",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 544, DateTimeKind.Utc).AddTicks(807),
                            Description = "Elektrik-Elektronik Mühendisliği Bölümü",
                            Faculty = "Mühendislik Fakültesi",
                            IsActive = true,
                            Name = "Elektrik-Elektronik Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 544, DateTimeKind.Utc).AddTicks(807)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "MM",
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 544, DateTimeKind.Utc).AddTicks(810),
                            Description = "Makine Mühendisliği Bölümü",
                            Faculty = "Mühendislik Fakültesi",
                            IsActive = true,
                            Name = "Makine Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 544, DateTimeKind.Utc).AddTicks(811)
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistrationData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("FailureEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal?>("FinalGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("GradePoint")
                        .HasColumnType("decimal(3,2)");

                    b.Property<decimal?>("HomeworkGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LetterGrade")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<decimal?>("MidtermGrade")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("WarningEmailSent")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.HasIndex("StudentId", "SectionId")
                        .IsUnique();

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e0a00001-0001-0001-0001-000000000001"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2535),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2410),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00001-0001-0001-0001-000000000001"),
                            Status = "Active",
                            StudentId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2602),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00002-0002-0002-0002-000000000002"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2676),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2673),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00002-0002-0002-0002-000000000002"),
                            Status = "Active",
                            StudentId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2676),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00003-0003-0003-0003-000000000003"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2679),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2679),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00003-0003-0003-0003-000000000003"),
                            Status = "Active",
                            StudentId = new Guid("d1111111-1111-1111-1111-111111111111"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2680),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00004-0004-0004-0004-000000000004"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2683),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2682),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00001-0001-0001-0001-000000000001"),
                            Status = "Active",
                            StudentId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2683),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00005-0005-0005-0005-000000000005"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2686),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2685),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00004-0004-0004-0004-000000000004"),
                            Status = "Active",
                            StudentId = new Guid("d2222222-2222-2222-2222-222222222222"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2686),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00006-0006-0006-0006-000000000006"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2689),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2689),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00002-0002-0002-0002-000000000002"),
                            Status = "Active",
                            StudentId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2689),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00007-0007-0007-0007-000000000007"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2692),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2692),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00003-0003-0003-0003-000000000003"),
                            Status = "Active",
                            StudentId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2693),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00008-0008-0008-0008-000000000008"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2696),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2695),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00005-0005-0005-0005-000000000005"),
                            Status = "Active",
                            StudentId = new Guid("d3333333-3333-3333-3333-333333333333"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2696),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00009-0009-0009-0009-000000000009"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2701),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2700),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00001-0001-0001-0001-000000000001"),
                            Status = "Active",
                            StudentId = new Guid("d4444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2701),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00010-0010-0010-0010-000000000010"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2704),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2704),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00005-0005-0005-0005-000000000005"),
                            Status = "Active",
                            StudentId = new Guid("d4444444-4444-4444-4444-444444444444"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2704),
                            WarningEmailSent = false
                        },
                        new
                        {
                            Id = new Guid("e0a00011-0011-0011-0011-000000000011"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2707),
                            EnrollmentDate = new DateTime(2025, 11, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2707),
                            FailureEmailSent = false,
                            SectionId = new Guid("5ec00006-0006-0006-0006-000000000006"),
                            Status = "Active",
                            StudentId = new Guid("d5555555-5555-5555-5555-555555555555"),
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 531, DateTimeKind.Utc).AddTicks(2708),
                            WarningEmailSent = false
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.ExcuseRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("SessionId");

                    b.HasIndex("StudentId", "SessionId")
                        .IsUnique();

                    b.ToTable("ExcuseRequests");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OfficeHours")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 945, DateTimeKind.Utc).AddTicks(6393),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeNumber = "F001",
                            OfficeHours = "Pazartesi 10:00-12:00, Çarşamba 14:00-16:00",
                            OfficeLocation = "A-101",
                            Specialization = "Web Programlama, Yazılım Mühendisliği",
                            Title = "AssociateProfessor",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 945, DateTimeKind.Utc).AddTicks(6478),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("fa222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 945, DateTimeKind.Utc).AddTicks(6560),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EmployeeNumber = "F002",
                            OfficeHours = "Salı 09:00-11:00, Perşembe 13:00-15:00",
                            OfficeLocation = "B-205",
                            Specialization = "Elektronik, Sinyal İşleme",
                            Title = "Professor",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 945, DateTimeKind.Utc).AddTicks(6561),
                            UserId = new Guid("f2222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SmartCampus.API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CGPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("IsScholarship")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CGPA = 3.45m,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3298),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.50m,
                            IsScholarship = true,
                            StudentNumber = "2021001",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3385),
                            UserId = new Guid("c1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CGPA = 3.15m,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3496),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.20m,
                            IsScholarship = false,
                            StudentNumber = "2021002",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3497),
                            UserId = new Guid("c2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CGPA = 3.75m,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3501),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.80m,
                            IsScholarship = true,
                            StudentNumber = "2021003",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3501),
                            UserId = new Guid("c3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            CGPA = 3.55m,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3505),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.60m,
                            IsScholarship = false,
                            StudentNumber = "2021004",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3505),
                            UserId = new Guid("c4444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-5555-5555-555555555555"),
                            CGPA = 2.85m,
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3518),
                            CurrentSemester = 5,
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EnrollmentYear = 2022,
                            GPA = 2.90m,
                            IsScholarship = false,
                            StudentNumber = "2022001",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 529, DateTimeKind.Utc).AddTicks(3519),
                            UserId = new Guid("c5555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.TwoFactorCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TempToken")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TwoFactorCodes");
                });

            modelBuilder.Entity("SmartCampus.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 715, DateTimeKind.Utc).AddTicks(4967),
                            Email = "admin@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$1K/LXMFAbfClakFchmGNI.EmC3p149DRq3WET5OlfgA/NxQxsCRJi",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 715, DateTimeKind.Utc).AddTicks(5115)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 830, DateTimeKind.Utc).AddTicks(3811),
                            Email = "mehmet.sevri@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Mehmet",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Sevri",
                            PasswordHash = "$2a$11$hYGSCgBp58nRU07DJeMK6.0z14boEkcd8ilvfQvvLeQ11hYu9SF7i",
                            Role = "Faculty",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 830, DateTimeKind.Utc).AddTicks(3817)
                        },
                        new
                        {
                            Id = new Guid("f2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 945, DateTimeKind.Utc).AddTicks(2927),
                            Email = "ayse.yilmaz@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Ayşe",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Yılmaz",
                            PasswordHash = "$2a$11$zMoFVHHPDJSAy.UdwOZZFOTZqhMIZu5jzY6HQK/P3SEexlEjBK9/m",
                            Role = "Faculty",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 2, 945, DateTimeKind.Utc).AddTicks(2933)
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 63, DateTimeKind.Utc).AddTicks(631),
                            Email = "zeki.erdem@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Zeki",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Erdem",
                            PasswordHash = "$2a$11$rD0k8zSSLGoLjs4x3qGm7e3odcOCLTpeB74UqDLaYwS1/lHoR7Kgm",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 63, DateTimeKind.Utc).AddTicks(639)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 185, DateTimeKind.Utc).AddTicks(2384),
                            Email = "mert.abdullahoglu@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Mert",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Abdullahoğlu",
                            PasswordHash = "$2a$11$tmPeCZ5R.H08YRoBrM9eEeFyrAfJWqo/oDZyVr.YjpYwPykAOLQ8q",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 185, DateTimeKind.Utc).AddTicks(2388)
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 299, DateTimeKind.Utc).AddTicks(975),
                            Email = "sena.kamiloglu@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Sena",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Kamiloğlu",
                            PasswordHash = "$2a$11$fwlR6zEpelQXxJIhpL0c5OnMhJI7u6RQNMTqLUTiy2HNzn7pCqwwC",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 299, DateTimeKind.Utc).AddTicks(1053)
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 413, DateTimeKind.Utc).AddTicks(5107),
                            Email = "sevval.asi@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Şevval",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Asi",
                            PasswordHash = "$2a$11$4ml/WCNN.qH6NdyFjA5r0.YPCgXbfCMk.3oPrzp/YGHArKb6.pk.y",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 413, DateTimeKind.Utc).AddTicks(5111)
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 528, DateTimeKind.Utc).AddTicks(336),
                            Email = "ali.veli@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Ali",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Veli",
                            PasswordHash = "$2a$11$aolt1CgloI2/bcMQkM7oiO0TBVfSUWU5zu3.b22fU1Le5doGn0HQG",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 14, 10, 31, 3, 528, DateTimeKind.Utc).AddTicks(341)
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.ActivityLog", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Announcement", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Author");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("SmartCampus.API.Models.AttendanceRecord", b =>
                {
                    b.HasOne("SmartCampus.API.Models.AttendanceSession", "Session")
                        .WithMany("Records")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.Student", "Student")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartCampus.API.Models.AttendanceSession", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Faculty", "Instructor")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.CourseSection", "Section")
                        .WithMany("AttendanceSessions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Course", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("SmartCampus.API.Models.CoursePrerequisite", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.Course", "PrerequisiteCourse")
                        .WithMany("RequiredFor")
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("SmartCampus.API.Models.CourseSection", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Classroom", "Classroom")
                        .WithMany("Sections")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartCampus.API.Models.Course", "Course")
                        .WithMany("Sections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.Faculty", "Instructor")
                        .WithMany("TeachingSections")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("Course");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("SmartCampus.API.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Enrollment", b =>
                {
                    b.HasOne("SmartCampus.API.Models.CourseSection", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartCampus.API.Models.ExcuseRequest", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Faculty", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SmartCampus.API.Models.AttendanceSession", "Session")
                        .WithMany("ExcuseRequests")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.Student", "Student")
                        .WithMany("ExcuseRequests")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reviewer");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Faculty", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Department", "Department")
                        .WithMany("FacultyMembers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithOne("Faculty")
                        .HasForeignKey("SmartCampus.API.Models.Faculty", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Student", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SmartCampus.API.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.TwoFactorCode", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.AttendanceSession", b =>
                {
                    b.Navigation("ExcuseRequests");

                    b.Navigation("Records");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Classroom", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Course", b =>
                {
                    b.Navigation("Prerequisites");

                    b.Navigation("RequiredFor");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("SmartCampus.API.Models.CourseSection", b =>
                {
                    b.Navigation("AttendanceSessions");

                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("FacultyMembers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Faculty", b =>
                {
                    b.Navigation("AttendanceSessions");

                    b.Navigation("TeachingSections");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Student", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Enrollments");

                    b.Navigation("ExcuseRequests");
                });

            modelBuilder.Entity("SmartCampus.API.Models.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("Faculty");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
