// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCampus.API.Data;

#nullable disable

namespace SmartCampus.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210140958_AddAccountLockout")]
    partial class AddAccountLockout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartCampus.API.Models.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "BM",
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 56, 901, DateTimeKind.Utc).AddTicks(548),
                            Description = "Bilgisayar Mühendisliği Bölümü",
                            Faculty = "Mühendislik Fakültesi",
                            IsActive = true,
                            Name = "Bilgisayar Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 56, 901, DateTimeKind.Utc).AddTicks(629)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "EEM",
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 56, 901, DateTimeKind.Utc).AddTicks(703),
                            Description = "Elektrik-Elektronik Mühendisliği Bölümü",
                            Faculty = "Mühendislik Fakültesi",
                            IsActive = true,
                            Name = "Elektrik-Elektronik Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 56, 901, DateTimeKind.Utc).AddTicks(703)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "MM",
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 56, 901, DateTimeKind.Utc).AddTicks(706),
                            Description = "Makine Mühendisliği Bölümü",
                            Faculty = "Mühendislik Fakültesi",
                            IsActive = true,
                            Name = "Makine Mühendisliği",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 56, 901, DateTimeKind.Utc).AddTicks(706)
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RegistrationData")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationTokens");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("OfficeHours")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OfficeLocation")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Faculties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 295, DateTimeKind.Utc).AddTicks(3213),
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EmployeeNumber = "F001",
                            OfficeHours = "Pazartesi 10:00-12:00, Çarşamba 14:00-16:00",
                            OfficeLocation = "A-101",
                            Specialization = "Web Programlama, Yazılım Mühendisliği",
                            Title = "AssociateProfessor",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 295, DateTimeKind.Utc).AddTicks(3311),
                            UserId = new Guid("f1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("fa222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 295, DateTimeKind.Utc).AddTicks(3392),
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EmployeeNumber = "F002",
                            OfficeHours = "Salı 09:00-11:00, Perşembe 13:00-15:00",
                            OfficeLocation = "B-205",
                            Specialization = "Elektronik, Sinyal İşleme",
                            Title = "Professor",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 295, DateTimeKind.Utc).AddTicks(3392),
                            UserId = new Guid("f2222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SmartCampus.API.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RevokedReason")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("CGPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("char(36)");

                    b.Property<int>("EnrollmentYear")
                        .HasColumnType("int");

                    b.Property<decimal>("GPA")
                        .HasColumnType("decimal(3,2)");

                    b.Property<bool>("IsScholarship")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1111111-1111-1111-1111-111111111111"),
                            CGPA = 3.45m,
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3141),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.50m,
                            IsScholarship = true,
                            StudentNumber = "2021001",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3231),
                            UserId = new Guid("c1111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            Id = new Guid("d2222222-2222-2222-2222-222222222222"),
                            CGPA = 3.15m,
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3338),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.20m,
                            IsScholarship = false,
                            StudentNumber = "2021002",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3339),
                            UserId = new Guid("c2222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("d3333333-3333-3333-3333-333333333333"),
                            CGPA = 3.75m,
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3343),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.80m,
                            IsScholarship = true,
                            StudentNumber = "2021003",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3343),
                            UserId = new Guid("c3333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("d4444444-4444-4444-4444-444444444444"),
                            CGPA = 3.55m,
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3346),
                            CurrentSemester = 7,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentYear = 2021,
                            GPA = 3.60m,
                            IsScholarship = false,
                            StudentNumber = "2021004",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3347),
                            UserId = new Guid("c4444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("d5555555-5555-5555-5555-555555555555"),
                            CGPA = 2.85m,
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3366),
                            CurrentSemester = 5,
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            EnrollmentYear = 2022,
                            GPA = 2.90m,
                            IsScholarship = false,
                            StudentNumber = "2022001",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 866, DateTimeKind.Utc).AddTicks(3366),
                            UserId = new Guid("c5555555-5555-5555-5555-555555555555")
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("LockoutEndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 63, DateTimeKind.Utc).AddTicks(1617),
                            Email = "admin@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Admin",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$woFIq/nSuIJ1dYfnDufiCucXwo.ToSF2vpBpxBJWNRT9e9DcTedQG",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 63, DateTimeKind.Utc).AddTicks(1934)
                        },
                        new
                        {
                            Id = new Guid("f1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 180, DateTimeKind.Utc).AddTicks(8720),
                            Email = "mehmet.sevri@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Mehmet",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Sevri",
                            PasswordHash = "$2a$11$xuDSEPXho1DbcmX6fSjMy.jJdERxXSPj2p//evBNcWyjH4G8pBf5C",
                            Role = "Faculty",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 180, DateTimeKind.Utc).AddTicks(8725)
                        },
                        new
                        {
                            Id = new Guid("f2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 295, DateTimeKind.Utc).AddTicks(314),
                            Email = "ayse.yilmaz@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Ayşe",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Yılmaz",
                            PasswordHash = "$2a$11$9Tq9jVGlAKAUTbQqCo2/meXzDXjrr6ajMNWMA8HUaOv.CFv5O/61C",
                            Role = "Faculty",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 295, DateTimeKind.Utc).AddTicks(318)
                        },
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 409, DateTimeKind.Utc).AddTicks(2865),
                            Email = "zeki.erdem@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Zeki",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Erdem",
                            PasswordHash = "$2a$11$MT0NmRu/wWSYslsFuz6.feJf90.HpoenGX5tZv83CiYhS1Eo4BN7q",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 409, DateTimeKind.Utc).AddTicks(2869)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 523, DateTimeKind.Utc).AddTicks(6899),
                            Email = "mert.abdullahoglu@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Mert",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Abdullahoğlu",
                            PasswordHash = "$2a$11$qXIkjZtb.R3uUMiIIc.1fOTQCF45hFnU9vNnETcPA0JAifYitkkH6",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 523, DateTimeKind.Utc).AddTicks(6904)
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 637, DateTimeKind.Utc).AddTicks(4765),
                            Email = "sena.kamiloglu@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Sena",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Kamiloğlu",
                            PasswordHash = "$2a$11$o5KW4kFNCC3XIRAtyz42SeMkEuhQiIs9FwRvzrAXg35CzK06/.JXG",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 637, DateTimeKind.Utc).AddTicks(4832)
                        },
                        new
                        {
                            Id = new Guid("c4444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 751, DateTimeKind.Utc).AddTicks(3849),
                            Email = "sevval.asi@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Şevval",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Asi",
                            PasswordHash = "$2a$11$pTSdtF2u3tcSwyCQhpyQ5uyJgYWnb6w9qc7pUr7Ry8dZtI8xHP9Ry",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 751, DateTimeKind.Utc).AddTicks(3852)
                        },
                        new
                        {
                            Id = new Guid("c5555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 865, DateTimeKind.Utc).AddTicks(987),
                            Email = "ali.veli@smartcampus.com",
                            FailedLoginAttempts = 0,
                            FirstName = "Ali",
                            IsActive = true,
                            IsEmailVerified = true,
                            LastName = "Veli",
                            PasswordHash = "$2a$11$U/b4s4nRXieLT6URFbA/Xuslx.d86inqqNB0967QofzSVVTHj8KjS",
                            Role = "Student",
                            UpdatedAt = new DateTime(2025, 12, 10, 14, 9, 57, 865, DateTimeKind.Utc).AddTicks(990)
                        });
                });

            modelBuilder.Entity("SmartCampus.API.Models.ActivityLog", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.EmailVerificationToken", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany("EmailVerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Faculty", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Department", "Department")
                        .WithMany("FacultyMembers")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithOne("Faculty")
                        .HasForeignKey("SmartCampus.API.Models.Faculty", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.PasswordResetToken", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.RefreshToken", b =>
                {
                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Student", b =>
                {
                    b.HasOne("SmartCampus.API.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartCampus.API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("SmartCampus.API.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartCampus.API.Models.Department", b =>
                {
                    b.Navigation("FacultyMembers");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SmartCampus.API.Models.User", b =>
                {
                    b.Navigation("EmailVerificationTokens");

                    b.Navigation("Faculty");

                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
